import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sidebarIntro: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      items: [
        { type: 'doc', id: 'intro' },
        { type: 'doc', id: 'regras-de-escrita' },
      ],
    },
    {
      type: 'category',
      label: 'Content',
      collapsible: false,
      description: 'Description',
      items: [
        { type: 'autogenerated', dirName: 'content' },
      ],
    },
  ],

};

export default sidebars;
